apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-demo-enrichment
  namespace: tms-demo
  labels:
    app: tms-demo-enrichment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-demo-enrichment
  template:
    metadata:
      labels:
        app: tms-demo-enrichment
    spec:
      containers:      
      - name: tms-demo-enrichment
        image: ssaily/tms-demo-processing:0.4.5
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: enrichment
          - name: JAVA_OPTS
            value: "-javaagent:./jmx_prometheus_javaagent-0.16.1.jar=9091:kafka-client.yaml"
        envFrom:
          - secretRef:
              name: kafka-secrets        
          - secretRef: 
              name: tms-service-endpoint
        volumeMounts:
        - mountPath: /etc/streams/tms-processing-cert
          name: cert-volume
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: metrics
          containerPort: 9091
      volumes:
        - name: cert-volume
          secret:
            secretName: tms-processing-cert
            items:
            - key: client.keystore.p12
              path: client.keystore.p12
            - key: client.truststore.jks
              path: client.truststore.jks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-demo-calculations
  namespace: tms-demo
  labels:
    app: tms-demo-calculations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-demo-calculations
  template:
    metadata:
      labels:
        app: tms-demo-calculations
    spec:
      containers:      
      - name: tms-demo-calculations
        image: ssaily/tms-demo-processing:0.4.5
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: calculations
          - name: JAVA_OPTS
            value: "-javaagent:./jmx_prometheus_javaagent-0.16.1.jar=9091:kafka-client.yaml"
        envFrom:
          - secretRef:
              name: kafka-secrets        
          - secretRef: 
              name: tms-service-endpoint
        volumeMounts:
        - mountPath: /etc/streams/tms-processing-cert
          name: tms-processing-cert
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "100m"
        imagePullPolicy: Always      
      volumes:
        - name: tms-processing-cert
          secret:
            secretName: tms-processing-cert
            items:
            - key: client.keystore.p12
              path: client.keystore.p12
            - key: client.truststore.jks
              path: client.truststore.jks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-demo-multivariate
  namespace: tms-demo
  labels:
    app: tms-demo-multivariate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-demo-multivariate
  template:
    metadata:
      labels:
        app: tms-demo-multivariate
    spec:
      containers:      
      - name: tms-demo-multivariate
        image: ssaily/tms-demo-processing:0.4.5
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: multivariate
          - name: JAVA_OPTS
            value: "-javaagent:./jmx_prometheus_javaagent-0.16.1.jar=9091:kafka-client.yaml"
        envFrom:
          - secretRef:
              name: kafka-secrets        
          - secretRef: 
              name: tms-service-endpoint
        volumeMounts:
        - mountPath: /etc/streams/tms-processing-cert
          name: tms-processing-cert
        resources:
          limits:
            memory: 1024Mi
            cpu: "2"
          requests:
            memory: 256Mi
            cpu: "100m"
        imagePullPolicy: Always      
      volumes:
        - name: tms-processing-cert
          secret:
            secretName: tms-processing-cert
            items:
            - key: client.keystore.p12
              path: client.keystore.p12
            - key: client.truststore.jks
              path: client.truststore.jks
---
apiVersion: v1
kind: Service
metadata:
  name: tms-demo-enrichment-svc
  namespace: tms-demo
  labels:
    app: tms-demo-enrichment
spec:
  ports:
    - name: metrics
      port: 9091
  selector:
    app: tms-demo-enrichment
---
apiVersion: v1
kind: Service
metadata:
  name: tms-demo-calculations-svc
  namespace: tms-demo
  labels:
    app: tms-demo-calculations
spec:
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: tms-demo-calculations
---
apiVersion: v1
kind: Service
metadata:
  name: tms-demo-multivariate-svc
  namespace: tms-demo
  labels:
    app: tms-demo-multivariate
spec:
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: tms-demo-multivariate
